<a href="https://colab.research.google.com/github/Hansika2346/STML_2303A52409/blob/main/finalprojectstatml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
d=pd.read_csv('/content/tourism_dataset (2).csv')
print(d)

        Location Country    Category  Visitors  Rating    Revenue  \
0     kuBZRkVsAR   India      Nature    948853    1.32   84388.38   
1     aHKUXhjzTo     USA  Historical    813627    2.01  802625.60   
2     dlrdYtJFTA  Brazil      Nature    508673    1.42  338777.11   
3     DxmlzdGkHK  Brazil  Historical    623329    1.09  295183.60   
4     WJCCQlepnz  France    Cultural    124867    1.43  547893.24   
...          ...     ...         ...       ...     ...        ...   
5984  xAzwnVKAqz     USA       Urban    828137    1.97  132848.78   
5985  IfKotyaJFC  France      Nature    276317    3.53  325183.96   
5986  bPyubCWGgA   Egypt       Beach    809198    3.37  927336.50   
5987  kkWIucpBnu   Egypt    Cultural    808303    2.52  115791.43   
5988  gHXUrdticm  France    Cultural     40939    4.65  957026.85   

     Accommodation_Available  
0                        Yes  
1                         No  
2                        Yes  
3                        Yes  
4               

In [ ]:
d.isnull().sum()

Location                   0
Country                    0
Category                   0
Visitors                   0
Rating                     0
Revenue                    0
Accommodation_Available    0
dtype: int64

In [ ]:
y=d['Accommodation_Available']
print(y)

0       Yes
1        No
2       Yes
3       Yes
4        No
       ... 
5984     No
5985    Yes
5986     No
5987    Yes
5988    Yes
Name: Accommodation_Available, Length: 5989, dtype: object


In [ ]:
x=d.drop('Accommodation_Available',axis=1)
print(x)

        Location Country    Category  Visitors  Rating    Revenue
0     kuBZRkVsAR   India      Nature    948853    1.32   84388.38
1     aHKUXhjzTo     USA  Historical    813627    2.01  802625.60
2     dlrdYtJFTA  Brazil      Nature    508673    1.42  338777.11
3     DxmlzdGkHK  Brazil  Historical    623329    1.09  295183.60
4     WJCCQlepnz  France    Cultural    124867    1.43  547893.24
...          ...     ...         ...       ...     ...        ...
5984  xAzwnVKAqz     USA       Urban    828137    1.97  132848.78
5985  IfKotyaJFC  France      Nature    276317    3.53  325183.96
5986  bPyubCWGgA   Egypt       Beach    809198    3.37  927336.50
5987  kkWIucpBnu   Egypt    Cultural    808303    2.52  115791.43
5988  gHXUrdticm  France    Cultural     40939    4.65  957026.85

[5989 rows x 6 columns]


In [ ]:
x.dtypes

Location     object
Country      object
Category     object
Visitors      int64
Rating      float64
Revenue     float64
dtype: object

In [ ]:
for column in x.columns:
    print(x[column].value_counts())

Location
kuBZRkVsAR    1
nhBhGoMHDe    1
YspVRTPULE    1
NxsobMMCiE    1
NrkusOEBVk    1
             ..
amZohYzBPa    1
STRyQjwLNi    1
zMCXXQKwWH    1
ythutjqKUZ    1
gHXUrdticm    1
Name: count, Length: 5989, dtype: int64
Country
Egypt        912
India        896
France       857
USA          848
Brazil       840
Australia    830
China        806
Name: count, dtype: int64
Category
Adventure     1037
Urban         1006
Cultural       998
Beach          998
Historical     994
Nature         956
Name: count, dtype: int64
Visitors
649167    2
590896    2
577353    2
733011    2
450785    2
         ..
487014    1
583867    1
976128    1
274442    1
40939     1
Name: count, Length: 5969, dtype: int64
Rating
3.66    28
4.15    25
1.81    25
2.91    24
3.50    24
        ..
4.08     7
2.33     7
1.66     7
4.99     6
4.59     5
Name: count, Length: 401, dtype: int64
Revenue
84388.38     1
95896.08     1
673652.73    1
560668.69    1
797614.52    1
            ..
186767.62    1
724890.12   

In [ ]:
for column in x.columns:
    print(x[column].unique())

['kuBZRkVsAR' 'aHKUXhjzTo' 'dlrdYtJFTA' ... 'bPyubCWGgA' 'kkWIucpBnu'
 'gHXUrdticm']
['India' 'USA' 'Brazil' 'France' 'Egypt' 'China' 'Australia']
['Nature' 'Historical' 'Cultural' 'Beach' 'Adventure' 'Urban']
[948853 813627 508673 ... 809198 808303  40939]
[1.32 2.01 1.42 1.09 1.43 2.19 3.92 2.5  4.1  1.98 4.2  1.76 1.06 2.21
 3.41 3.63 2.98 1.34 4.65 1.15 4.36 3.45 4.33 1.21 3.6  4.24 1.87 1.17
 2.26 3.67 3.86 4.97 3.9  2.16 1.07 2.81 2.58 2.14 3.05 2.84 3.74 2.25
 3.4  1.16 3.24 1.9  3.55 2.4  3.32 3.82 2.93 4.82 1.1  2.   4.3  3.78
 1.01 1.4  4.89 1.5  1.96 4.73 4.96 4.16 1.91 3.75 2.77 4.44 1.   3.57
 2.8  4.54 3.7  3.58 1.63 4.76 4.17 3.94 4.38 4.93 2.17 2.56 4.85 3.47
 3.28 1.48 4.78 3.89 2.27 2.3  2.11 3.44 3.61 3.13 4.69 3.68 3.77 3.03
 4.84 2.61 3.62 2.29 4.09 3.97 1.23 2.47 2.64 3.37 4.01 1.85 1.03 4.88
 2.97 2.62 4.28 3.02 1.59 1.86 1.12 3.51 1.8  1.53 2.52 3.91 1.65 4.67
 1.67 1.37 3.43 3.8  2.87 1.45 3.96 1.52 3.95 3.66 4.81 1.79 4.74 2.95
 2.92 4.46 3.64 1.73 2.08 2.89 4

In [ ]:

location_mapping = {location: i for i, location in enumerate(x['Location'].unique())}
country_mapping = {country: i for i, country in enumerate(x['Country'].unique())}
category_mapping = {category: i for i, category in enumerate(x['Category'].unique())}

x['Location'] = x['Location'].map(location_mapping)
x['Country'] = x['Country'].map(country_mapping)
x['Category'] = x['Category'].map(category_mapping)


In [ ]:
x.dtypes

Location      int64
Country       int64
Category      int64
Visitors      int64
Rating      float64
Revenue     float64
dtype: object

In [ ]:
x.head()

Location  Country  Category  Visitors  Rating    Revenue
0         0        0         0    948853    1.32   84388.38
1         1        1         1    813627    2.01  802625.60
2         2        2         0    508673    1.42  338777.11
3         3        2         1    623329    1.09  295183.60
4         4        3         2    124867    1.43  547893.24

In [ ]:
d.isnull().sum()


Location                   0
Country                    0
Category                   0
Visitors                   0
Rating                     0
Revenue                    0
Accommodation_Available    0
dtype: int64

In [ ]:
y.replace(['Yes', 'No'], [1, 0], inplace=True)
print(y)

0       1
1       0
2       1
3       1
4       0
       ..
5984    0
5985    1
5986    0
5987    1
5988    1
Name: Accommodation_Available, Length: 5989, dtype: int64


<ipython-input-223-18932f521dc7>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y.replace(['Yes', 'No'], [1, 0], inplace=True)


In [ ]:
Y=d['Accommodation_Available']
print(Y)

0       1
1       0
2       1
3       1
4       0
       ..
5984    0
5985    1
5986    0
5987    1
5988    1
Name: Accommodation_Available, Length: 5989, dtype: int64


SPLITING

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)


In [ ]:
print(X_train)

      Location  Country  Category  Visitors  Rating    Revenue
1027      1027        2         2    952995    3.69  615759.49
2415      2415        3         2    967505    3.90  169108.35
2136      2136        1         5    797886    2.98  412309.58
4306      4306        6         5    129676    2.67  122661.83
60          60        3         3    958216    2.84   93854.02
...        ...      ...       ...       ...     ...        ...
3881      3881        3         1    249926    1.57  795261.13
4436      4436        2         4    909643    4.41  816279.55
4375      4375        1         0    378263    3.38  923406.82
4232      4232        4         3    181354    2.62  610892.24
2590      2590        6         5     96029    4.04  997433.45

[4791 rows x 6 columns]


In [ ]:
print(X_test)

      Location  Country  Category  Visitors  Rating    Revenue
3050      3050        2         2    736359    3.97  724374.62
3672      3672        0         3    866643    3.73  910738.24
3681      3681        6         2    170266    3.45  654440.80
564        564        1         3     98635    2.37  336661.00
5984      5984        1         5    828137    1.97  132848.78
...        ...      ...       ...       ...     ...        ...
732        732        2         4    167498    1.81  477927.22
5003      5003        1         4    781927    4.70  240821.18
5292      5292        4         4    772021    3.58  385954.14
5709      5709        1         0    519608    4.07  789900.50
4387      4387        6         2    215369    1.23  305796.21

[1198 rows x 6 columns]


In [ ]:

print(Y_train)

1027    1
2415    1
2136    1
4306    0
60      0
       ..
3881    0
4436    0
4375    1
4232    0
2590    1
Name: Accommodation_Available, Length: 4791, dtype: int64


In [ ]:
print(Y_test)

3050    1
3672    1
3681    0
564     1
5984    0
       ..
732     1
5003    0
5292    1
5709    1
4387    0
Name: Accommodation_Available, Length: 1198, dtype: int64


In [ ]:
y.value_counts()

Accommodation_Available
1    3013
0    2976
Name: count, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:

from sklearn.linear_model import LogisticRegression
lr2=LogisticRegression(max_iter=1000)
lr2.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

In [ ]:
yp1=lr2.predict(X_test)
print(accuracy_score(Y_test,yp1))

0.4991652754590985


In [ ]:
print(confusion_matrix(Y_test,yp1))

[[307 292]
 [308 291]]


In [ ]:
print(classification_report(Y_test,yp1))

              precision    recall  f1-score   support

           0       0.50      0.51      0.51       599
           1       0.50      0.49      0.49       599

    accuracy                           0.50      1198
   macro avg       0.50      0.50      0.50      1198
weighted avg       0.50      0.50      0.50      1198



In [ ]:
##PERCEPTRON CLASSIFICATION
from sklearn.linear_model import Perceptron
lr1=Perceptron()
lr1.fit(X_train,Y_train)

Perceptron()

In [ ]:
yp1=lr1.predict(X_test)
print(accuracy_score(Y_test,yp1))

0.5


In [ ]:
print(confusion_matrix(Y_test,yp1))

[[599   0]
 [599   0]]


In [ ]:
print(classification_report(Y_test,yp1))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67       599
           1       0.00      0.00      0.00       599

    accuracy                           0.50      1198
   macro avg       0.25      0.50      0.33      1198
weighted avg       0.25      0.50      0.33      1198



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
##SVM CLASSIFICATION
from sklearn.svm import SVC
lr=SVC()
lr.fit(X_train,Y_train)

SVC()

In [ ]:
yp=lr.predict(X_test)
print(accuracy_score(Y_test,yp))

0.505008347245409


In [ ]:
print(confusion_matrix(Y_test,yp))

[[219 380]
 [213 386]]


In [ ]:
print(classification_report(Y_test,yp))

              precision    recall  f1-score   support

           0       0.51      0.37      0.42       599
           1       0.50      0.64      0.57       599

    accuracy                           0.51      1198
   macro avg       0.51      0.51      0.50      1198
weighted avg       0.51      0.51      0.50      1198

